name: gpas-cli
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - python=3.10
  - read-it-and-keep
  - samtools=1.15.1
  - pip:
    - git+https://github.com/GlobalPathogenAnalysisService/gpas-cli.git#egg=gpas
