name: gpas-cli
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - python=3.10
  - read-it-and-keep
  - samtools
  - pip:
    - git+https://github.com/GenomePathogenAnalysisService/gpas-uploader.git#egg=gpas_uploader
    - git+https://github.com/GenomePathogenAnalysisService/gpas-cli.git#egg=gpas
