name: gpas-cli-sars2-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - read-it-and-keep>=0.3.0
  - samtools>=1.15.1
  - pytest
  - pytest-cov
  - black
  - pre-commit
  - mypy
  - python-build
  - pip:
    - pyinstaller==5.6.2
    - git+https://github.com/GlobalPathogenAnalysisService/gpas-cli.git#egg=gpas
