name: tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge, bioconda
      - name: Install
        run: |
          conda install samtools read-it-and-keep pytest
          pip install .
          pip install git+https://github.com/GenomePathogenAnalysisService/gpas-uploader.git
      - name: Test
        run: |
          pytest
